### ISSUE TITLE
Full write (-W) of just-read image?

### ISSUE THREAD

**Issue by Tunas1337** [sq5bpf/k5prog#1]
I noticed the warning that says -W is "sure to brick your radio." Is this true? Would using that command to flash a just-read fresh, unmodified image really brick the radio? If so, why, when the data is the same as what's already there?

Also, I am confused about whether -W uses different instructions than -w, or it just flashes all regions instead of only the ones touched by the CPS software.

**Comment by sq5bpf** [comment]
Ok, i confess: it didn't brick my radio (yet!). But be extra careful. 

The -w option uses a list of memory locations that the original software uses on my radio (maybe the list of locations depends on the configuration, I don't know yet).

The -W option just writes everything. It is also faster because it uses a bigger block size.

The memory image doesn't have any checksum as far as i've noticed. So for example you can edit the banner or the channel names, upload it into the radio and it will work. Probably should write this in the docs.

**Comment by sq5bpf** [comment]
BTW is someone bricks their radio, or causes it to malfunction in any way, then please tell me what you did exactly, and what are the effects.

Also it would be great it people sent me a few eeprom images from radios that they just bought. This way we could compare the images and see if there is any calibration data there.

**Comment by fagci** [comment]
Hello =)

I've got a brick, but not with this tool. Flashed bigger file, which I got with Ghidra software. Tried to replace variable in single location and actually got huge block of data. Something goes wrong and radio can't boot into flash mode (LED not turns on).

Tried to flash with your tool with `-W` option, but no luck: read timeout.

Do you get same brick some time?

**Comment by sq5bpf** [comment]
Hi,

I didn't manage to brick my radio (yet!). But k5prog doesn't support reading/writing flash yet, so you can't load firmware with it and try to recover this way.
I doubt this would work anyway, unless there is some secret secondary recovery bootloader in the radio. You might have better luck with JTAG. 

Now that you have a brick, you have a great opportunity to do some hardware reverse engineering :)
BTW did you try to read the eeprom with k5prog? If yes, please send it to me via email, i'd like to compare it with mine.

**Comment by fagci** [comment]
Tried but no luck: read_timeout, k5_receive err read1.
I went to k5prog after brick, so... =)

**Comment by fagci** [comment]
Also, if someone need, there is [Ghidra](https://github.com/NationalSecurityAgency/ghidra) project & broken firmware:
https://drive.google.com/drive/folders/1-0MGJmFBjUv0rzkr5karLEftw48H4L24?usp=share_link
