### ISSUE TITLE
Flash fails with QS UV-5R+ (4.00.01.4 bootloader)

### ISSUE THREAD

**Issue by OK2MOP** [sq5bpf/k5prog#11]
Hello,
just letting know, that the Quansheng UV-5Rs have (together with a new v4.00.01 firmware), a **4.00.01.4** bootloader, which, unfortunately, has to receive correct bytes in writeflash[4..7] (not the default _0x8a 0x8d 0x9f 0x1d_). 

From my debugging of original communication with radio, they seem to be dependent on the firmware version, sent to the radio in the initial packet, but I did not find out how.  Initial hello packet from radio bootloader looks as follows:

`00000000: 18 05 20 00 01 02 02 06 1c 53 50 4a 37 47 ff 0f  .. ......SPJ7G..`
`00000010: 3f 00 5b 00 34 2e 30 30 2e 30 31 00 34 0a 00 00  ?.[.4.00.01.4...`
`00000020: 00 00 00 20                                      ... ` 

or (probably second radio)
`0x000000: 18 05 20 00 01 02 02 0b 0c 53 46 34 52 59 ff 02   .. ......SF4RY.. `  
`0x000010: 5a 00 62 00 34 2e 30 30 2e 30 31 00 34 0a 00 00   Z.b.4.00.01.4...`   
`0x000020: 00 00 00 20                                       ...` 

Result is that flashing is not done and bad packet is obtained as a reply to the first flash packet and nothing is written to flash

**Comment by OK2MOP** [comment]
### Decrypted example exchange (OSFW-501b651) from stock flasher

**First packet sent by stock flasher with firmware ID sent**
`00000000: 30 05 10 00 2a 4f 53 46 57 2d 35 30 31 62 36 35  0...*OSFW-501b651`
`00000010: 31 00 00 00 4e f3                                1...N.`

**Hello packets from previous post appear**
`0x000000: 18 05 20 00 01 02 02 0b 0c 53 46 34 52 59 ff 02   .. ......SF4RY..`   
`0x000010: 5a 00 62 00 34 2e 30 30 2e 30 31 00 34 0a 00 00   Z.b.4.00.01.4...`   
`0x000020: 00 00 00 20                                       ... `

**First flashing packet**, writeflash[4..7] is **0xD3 0xE2 0xCC 0x17**

`00000000: 19 05 0c 01 d3 e2 cc 17 00 00 e4 00 00 01 00 00  ................`
`00000010: f0 3f 00 20 0b 01 00 00 c1 00 00 00 c3 00 00 00  .?. ............`
`00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................`
`00000030: 00 00 00 00 00 00 00 00 00 00 00 00 c5 00 00 00  ................`
`00000040: 00 00 00 00 00 00 00 00 c7 00 00 00 d9 a5 00 00  ................`
`00000050: cb 00 00 00 cd 00 00 00 cf 00 00 00 d1 00 00 00  ................`
`00000060: d3 00 00 00 d5 00 00 00 d7 00 00 00 d9 00 00 00  ................`
`00000070: db 00 00 00 dd 00 00 00 df 00 00 00 e1 00 00 00  ................`
`00000080: e3 00 00 00 e5 00 00 00 e7 00 00 00 e9 00 00 00  ................`
`00000090: eb 00 00 00 ed 00 00 00 ef 00 00 00 f1 00 00 00  ................`
`000000a0: f3 00 00 00 f5 00 00 00 f7 00 00 00 f9 00 00 00  ................`
`000000b0: fb 00 00 00 fd 00 00 00 ff 00 00 00 01 01 00 00  ................`
`000000c0: 03 01 00 00 05 01 00 00 07 01 00 00 09 01 00 00  ................`
`000000d0: fe e7 fe e7 fe e7 fe e7 70 47 fe e7 fe e7 fe e7  ........pG......`
`000000e0: fe e7 fe e7 fe e7 fe e7 fe e7 fe e7 fe e7 fe e7  ................`
`000000f0: fe e7 fe e7 fe e7 fe e7 fe e7 fe e7 fe e7 fe e7  ................`
`00000100: fe e7 fe e7 fe e7 fe e7 fe e7 fe e7 fe e7 fe e7  ................`
`00000110: bd e3                                            ..`

**Flashing reply** (check in flasher would indicate confirmation is OK)
`00000000: 1a 05 08 00 d3 e2 cc 17 00 00 00 00              ............`

**Comment by LZ2DMV** [comment]
Just an assumption, but could this be because the firmware version sent from k5prog is hardcoded to 2.01.23 [here](https://github.com/sq5bpf/k5prog/blob/551d8a8cfe187d09ab3c07fbdf6efcb4cafc58ab/k5prog.c#L630)?

Try changing it to 4.00.01 and try again?

If it doesn't work again, change to 4.00.**02**, in case the bootloader is checking for a higher version.

**Comment by sq5bpf** [comment]
Actually you can just set a * as the first character, and all known bootloaders will accept it.

Check the latest version which has this wildcard string.  I've also added an option to set the bootloader string if you want to experiment.

Report back if it works for you, i only have radios with ver 2 bootloader.

**Comment by OK2MOP** [comment]
Hello, I can confirm that flashing now works.
As a side note, there is now a typo in k5prog.c:1046:101: `%s` should be `%x` (see compilation warning after `make clean` and `make`). I actually forgot that the version has to be hardcoded in the code since unencrypted flash is being read from disk.

Otherwise the issue may be closed. 

Thanks.

**Comment by sq5bpf** [comment]
Thanks for testing and for pointing out the error.
Added -Wall to the compile flags and fixed all of the warnings.
