### ISSUE TITLE
Little question about the uart sniffer tools

### ISSUE THREAD

**Issue by cheng3100** [sq5bpf/k5prog#2]
Hi I'm trying to understand how the reverse engineering is done to the uvk5. At first it need to sniffer the uart traffic between the official firmware tools and the uv5k. Could you recommand some good uart sniffer tools? I try to search on the internet but can't find a free and good one.

And by the way, after reading the script in the amnemonic's repo. I still don't know how the specific binary offset is found. For example, how did you guys know that at the offset 0x1804 is the code that limit the tx freq value? Is that really done through  reading the disassemble code?

**Comment by sq5bpf** [comment]
Hi 
I intend to release a writeup how the reverse engineering process was done from the point of getting a new radio, and not knowing anything about it, to the point of having enough info to write a chirp driver and a flashing tool.  But this will take some time.

Regarding finding stuff in the firmware, you can disassemble the firmware, but some things can be found using a simple search for the data if you know how it's represented. For example if you want to search for the 600MHz limit, then the data is probably something like a 32 bit number, little or big endian, which is something like 600 (* 1MHz), or 600000 (* 1kHz), or 60000000 (* 10Hz), or  600000000 (* 1Hz). In this case it's 60000000 (* 10Hz), and it's possible to guess this by looking at my memory map reverse engineering document (the representation is in 10Hz units, we can guess that the radio firmware probably does the same internally).
