### ISSUE TITLE
Zsh Parse error

### ISSUE THREAD

**Issue by ghost** [sq5bpf/k5prog#25]
I get:  zsh: parse error near `\n' when trying to execute on mac terminal. No idea of coding so can't resolve myself.
<img width="600" alt="Screenshot 2024-02-21 at 2 28 11 PM" src="https://github.com/sq5bpf/k5prog/assets/159571497/a1c8a054-6abe-495f-95b6-2c2379dc6772">

**Comment by sq5bpf** [comment]
I don't have a macbook to check, but i don't see why this error would happen.

Maybe you have copy-pasted the command from some website, including the \n (line feed) character, and this is the reason for the error. try to type it yourself and see if that helps.

Also please compile and use the latest version (0.9 now), 0.5 is very old.

**Comment by sq5bpf** [comment]
closing this for now. please re-open if you think this is still an issue. also please write if my theory is correct (copy-pasting from some shady website)
