### ISSUE TITLE
Cannot flash firmware image past 0xe500

### ISSUE THREAD

**Issue by Tunas1337** [sq5bpf/k5prog#5]
Title says it all. I have also attached a text file of the output of k5prog when trying to flash a firmware larger than 0xe500 with -vv.
[k5prog_firmware_update_output.txt](https://github.com/sq5bpf/k5prog/files/12207702/k5prog_firmware_update_output.txt)

**Comment by sq5bpf** [comment]
could you change around line 695:
        /* wait for a reply packet */
        l=50; //this was l=5; originally

and around line 719 add this:
                /* reply packet:
                 * 0x1a  0x5  0x8  0x0  0x8a  0x8d  0x9f  0x1d  0x0  0x0  0x0  0x0
                 */
printf("wait confirmation attempt %i\n",l); //add this line

and send me the log again?

**Comment by piotr022** [comment]
https://github.com/sq5bpf/k5prog/pull/7
this changes fix this problem

**Comment by OneOfEleven** [comment]
I've made a windows GUI version of your software and found the same problem, found I had to make the following change ..

[starts at line 680 of k5prog.c]

`
 writeflash[8]=(offset>>8)&0xff;
 writeflash[9]=offset&0xff;
 writeflash[10]=0xe6;
 writeflash[11]=0x00;
 writeflash[12]=len&0xff;
 writeflash[13]=(len>>8)&0xff;
 writeflash[14]=0x00;
 writeflash[15]=0x00;
`

into this ..

`
 writeflash[8]  = (offset >> 8) & 0xff;
 writeflash[9]  = (offset >> 0) & 0xff;
 writeflash[10] = 0xf0;                            // 'E6' was stopping the radio flashing past '0xE600'
 writeflash[11] = 0x00;
 writeflash[12] = (len >> 8) & 0xff;        // change to MS-Byte
 writeflash[13] = (len >> 0) & 0xff;        // change to LS-Byte
 writeflash[14] = 0x00;
 writeflash[15] = 0x00;
`

**Comment by sq5bpf** [comment]
Fixed. Big thanks for spotting which bytes to set :)
